---
# Non local deployments by quickstart
- name: Install delorian repos
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  vars_files:
    - vars/undercloud-traas.yaml
  vars:
    - release: master # install current master delorean
  roles:
    - repo-setup

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: true
  become: false
  vars_files:
    - vars/undercloud-traas.yaml
  roles:
    - undercloud-deploy
