---
# TODO Provision tasks with heat templates

- name: Generate new inventory for openstack provider
  hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  become: false
  vars_files:
    - vars/inventory-traas.yaml
  roles:
    - tripleo-inventory
