---
# Non local deployments by quickstart
- name: Run overcloud prep roles
  hosts: undercloud
  any_errors_fatal: true
  vars_files:
    - vars/overcloud-traas.yaml
  gather_facts: no
  become: true
  roles:
    - overcloud-prep-config
    - overcloud-prep-containers

- name:  Deploy the overcloud (multinode)
  any_errors_fatal: true
  hosts: undercloud
  gather_facts: yes
  become: false
  vars_files:
    - vars/overcloud-traas.yaml
  roles:
    - overcloud-deploy
  #TODO parametrize env vars for the deployed-server remaining roles
  environment:
    OVERCLOUD_ROLES: "ControllerDeployedServer"
    ControllerDeployedServer_hosts: "{{ lookup('env', 'CONTROLLER_HOSTS') }}"

- name: Add the overcloud nodes to the generated inventory
  any_errors_fatal: true
  hosts: undercloud
  gather_facts: yes
  vars_files:
    - vars/overcloud-traas.yaml
  become: false
  tags:
    - overcloud-deploy
  vars:
      inventory: all
  roles:
    - tripleo-inventory
